---

- name: Configure login settings
  ansible.builtin.lineinfile:
    dest: '{{ sshd_config_filepath }}'
    state: present
    regex: '#?^{{ item.key }} '
    line: '{{ item.key }} {{ item.value }}'
  loop:
    - key: PermitRootLogin
      value: '{{ sshd_root_login }}'
    - key: PasswordAuthentication
      value: '{{ sshd_password_login }}'
