---

- name: Set ssh version explicit
  ansible.builtin.lineinfile:
    path: '{{ sshd_config_filepath }}'
    state: present
    insertbefore: BOF
    regex: '^#?Protocol'
    line: 'Protocol {{ sshd_ssh_protocol_version }}'

- name: Set log level to {{ sshd_log_level }}
  ansible.builtin.lineinfile:
    path: '{{ sshd_config_filepath }}'
    state: present
    regex: '^#?LogLevel'
    line: 'LogLevel {{ sshd_log_level }}'

- name: Disable loading of other sshd config files
  ansible.builtin.lineinfile:
    dest: '{{ sshd_config_filepath }}'
    regexp: '^Include \/etc\/ssh\/sshd_config\.d\/\*\.conf'
    line: '#Include /etc/ssh/sshd_config.d/*.conf'
  notify: Restart sshd
  when: sshd_no_includes
