---

- name: Configure crypto settings
  ansible.builtin.lineinfile:
    dest: '{{ sshd_config_filepath }}'
    state: present
    regex: '#?^{{ item.key }} '
    line: '{{ item.key }} {{ item.value }}'
  loop:
    - key: Ciphers
      value: '{{ sshd_ciphers | join(",") }}'
    - key: KexAlgorithms
      value: '{{ sshd_keyexchange_algorithms | join(",") }}'
    - key: MACs
      value: '{{ sshd_macs | join(",") }}'
  notify: Restart sshd
